# Generated by Django 5.1.2 on 2024-10-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgroup',
            name='payout_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
