# Generated by Django 5.1.2 on 2024-10-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_article_quiz_video_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
